spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}://${DB_DOMAIN}/root
    name: ${DB_NAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081

custom:
  iex:
    protocol: ${IEX_PROTOCOL}
    host: ${IEX_HOST}
    token: ${IEX_TOKEN}