spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/root #${DB_HOST}://${DB_DOMAIN}/root
    name: root #${DB_NAME}
    password: root #${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081

custom:
  iex:
    url: ${IEX_PROTOCOL}://${IEX_HOST}/
    token: ${IEX_TOKEN}