spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        generate_statistics: false
        show_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

custom:
  iex:
    url: https://cloud.iexapis.com/
    token: ${IEX_TOKEN}

logging:
  level:
    ru.ersted.asyncmicroservice.client.IEXApiClient: info
    ru.ersted.asyncmicroservice.repository.impl.StockRepositoryImpl: info