spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/root #${DB_HOST}://${DB_DOMAIN}/root
    username: root #${DB_USERNAME}
    password: root #${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081

custom:
  iex:
    url: ${IEX_PROTOCOL}://${IEX_HOST}/ #https://cloud.iexapis.com
    token: ${IEX_TOKEN} #pk_879817dd19b44e1eb3d0960d02f17aba


app:
  threads:
    amount: 4